version: '3'

services:

  postgresql:
    container_name: postgresql
    hostname: postgresql
    privileged: true
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./db_data/test_db:/var/lib/postgresql/data
      - ./db_data/init.sh:/docker-entrypoint-initdb.d/init.sh
