// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/db.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePageRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePageRequest) Reset()         { *m = CreatePageRequest{} }
func (m *CreatePageRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePageRequest) ProtoMessage()    {}
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{0}
}

func (m *CreatePageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageRequest.Unmarshal(m, b)
}
func (m *CreatePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageRequest.Marshal(b, m, deterministic)
}
func (m *CreatePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageRequest.Merge(m, src)
}
func (m *CreatePageRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePageRequest.Size(m)
}
func (m *CreatePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageRequest proto.InternalMessageInfo

func (m *CreatePageRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreatePageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreatePageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePageResponse) Reset()         { *m = CreatePageResponse{} }
func (m *CreatePageResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePageResponse) ProtoMessage()    {}
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{1}
}

func (m *CreatePageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageResponse.Unmarshal(m, b)
}
func (m *CreatePageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageResponse.Marshal(b, m, deterministic)
}
func (m *CreatePageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageResponse.Merge(m, src)
}
func (m *CreatePageResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePageResponse.Size(m)
}
func (m *CreatePageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageResponse proto.InternalMessageInfo

func (m *CreatePageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePageResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPageRequest) Reset()         { *m = GetPageRequest{} }
func (m *GetPageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPageRequest) ProtoMessage()    {}
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{2}
}

func (m *GetPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageRequest.Unmarshal(m, b)
}
func (m *GetPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageRequest.Marshal(b, m, deterministic)
}
func (m *GetPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageRequest.Merge(m, src)
}
func (m *GetPageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPageRequest.Size(m)
}
func (m *GetPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageRequest proto.InternalMessageInfo

func (m *GetPageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPageRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetPageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPageResponse) Reset()         { *m = GetPageResponse{} }
func (m *GetPageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPageResponse) ProtoMessage()    {}
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{3}
}

func (m *GetPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageResponse.Unmarshal(m, b)
}
func (m *GetPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageResponse.Marshal(b, m, deterministic)
}
func (m *GetPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageResponse.Merge(m, src)
}
func (m *GetPageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPageResponse.Size(m)
}
func (m *GetPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageResponse proto.InternalMessageInfo

func (m *GetPageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetPageResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SimpleRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{4}
}

func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (m *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(m, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SimpleResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{5}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePageRequest)(nil), "grpc.CreatePageRequest")
	proto.RegisterType((*CreatePageResponse)(nil), "grpc.CreatePageResponse")
	proto.RegisterType((*GetPageRequest)(nil), "grpc.GetPageRequest")
	proto.RegisterType((*GetPageResponse)(nil), "grpc.GetPageResponse")
	proto.RegisterType((*SimpleRequest)(nil), "grpc.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "grpc.SimpleResponse")
}

func init() {
	proto.RegisterFile("proto/db.proto", fileDescriptor_903744a76531f483)
}

var fileDescriptor_903744a76531f483 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0xd2, 0x03, 0x33, 0x84, 0x58, 0xd2, 0x8b, 0x0a, 0x92, 0x95, 0xec, 0xb9,
	0x04, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x03, 0x12, 0xd3, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x72, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x40, 0x4c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0xb0,
	0x28, 0x8c, 0xab, 0x64, 0xc7, 0x25, 0x84, 0x6c, 0x40, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x48,
	0x7d, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0xd4, 0x14, 0x18, 0x57, 0x88, 0x8f, 0x8b, 0x29,
	0x33, 0x05, 0x6a, 0x08, 0x53, 0x66, 0x8a, 0x92, 0x11, 0x17, 0x9f, 0x7b, 0x6a, 0x09, 0xb2, 0xed,
	0x10, 0x15, 0x8c, 0x30, 0x15, 0x30, 0xd7, 0x30, 0xc1, 0x5d, 0xa3, 0x14, 0xce, 0xc5, 0x0f, 0xd7,
	0x43, 0xd0, 0x42, 0x0c, 0xed, 0xc8, 0x9e, 0x61, 0x46, 0xf5, 0x8c, 0x26, 0x17, 0x6f, 0x70, 0x66,
	0x6e, 0x41, 0x0e, 0xdc, 0x2d, 0x38, 0x8d, 0x55, 0xd2, 0xe2, 0xe2, 0x83, 0x29, 0x25, 0xe4, 0x04,
	0xa3, 0x7d, 0x8c, 0x5c, 0x6c, 0xee, 0x45, 0x05, 0xc9, 0x2e, 0x4e, 0x42, 0x8e, 0x5c, 0x5c, 0x88,
	0xe0, 0x12, 0x12, 0xd7, 0x03, 0x45, 0x82, 0x1e, 0x46, 0x0c, 0x48, 0x49, 0x60, 0x4a, 0x40, 0x6c,
	0x51, 0x62, 0x10, 0xb2, 0xe0, 0x62, 0x87, 0xfa, 0x5e, 0x48, 0x04, 0xa2, 0x0c, 0x35, 0x00, 0xa5,
	0x44, 0xd1, 0x44, 0xe1, 0x3a, 0xcd, 0xb9, 0x38, 0x82, 0x13, 0x2b, 0x3d, 0x52, 0x73, 0x72, 0xf2,
	0x85, 0x84, 0x21, 0x8a, 0x50, 0xbc, 0x2b, 0x25, 0x82, 0x2a, 0x08, 0xd3, 0x98, 0xc4, 0x06, 0x4e,
	0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x1a, 0x73, 0x14, 0x44, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcDBClient is the client API for GrpcDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcDBClient interface {
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error)
	SayHello(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type grpcDBClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcDBClient(cc grpc.ClientConnInterface) GrpcDBClient {
	return &grpcDBClient{cc}
}

func (c *grpcDBClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error) {
	out := new(CreatePageResponse)
	err := c.cc.Invoke(ctx, "/grpc.GrpcDB/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error) {
	out := new(GetPageResponse)
	err := c.cc.Invoke(ctx, "/grpc.GrpcDB/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcDBClient) SayHello(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/grpc.GrpcDB/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcDBServer is the server API for GrpcDB service.
type GrpcDBServer interface {
	CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error)
	GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error)
	SayHello(context.Context, *SimpleRequest) (*SimpleResponse, error)
}

// UnimplementedGrpcDBServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcDBServer struct {
}

func (*UnimplementedGrpcDBServer) CreatePage(ctx context.Context, req *CreatePageRequest) (*CreatePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (*UnimplementedGrpcDBServer) GetPage(ctx context.Context, req *GetPageRequest) (*GetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedGrpcDBServer) SayHello(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGrpcDBServer(s *grpc.Server, srv GrpcDBServer) {
	s.RegisterService(&_GrpcDB_serviceDesc, srv)
}

func _GrpcDB_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GrpcDB/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDB_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GrpcDB/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcDB_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDBServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GrpcDB/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDBServer).SayHello(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.GrpcDB",
	HandlerType: (*GrpcDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _GrpcDB_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _GrpcDB_GetPage_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _GrpcDB_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/db.proto",
}
